import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Message } from "./icons/Message";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        <p className='pl-12 px-4 text-black text-[16px] font-semibold'>
          AI tools
        </p>
        {children}
        <div className='flex items-end justify-end pr-13 pb-13'>
          <button className='w-12 h-12 bg-black rounded-full flex justify-center items-center '>
            <Message />
          </button>
        </div>
      </body>
    </html>
  );
}
